### ISSUE TITLE
Sending mail

### ISSUE THREAD

**Issue by mightydread** [riseuplabs/crabgrass-core#377]
Is there any log when sending emails fails?
These are my settings:
```
# e.g. smtp
email:
  delivery_method: :smtp
  smtp_settings:
    domain: localhost
    address: smtp.1und1.de
    port: 587
    authentication: :plain
    user_name: XXXX@fango.org
    password: XXXXXX
```
The setting for smtp I have from my provider
